# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        min:
            web_path: ~
            
    filter_sets:
        my_thumb_jpeg:
            format: jpeg
            quality: 80
            filters:
                thumbnail: { size: [1920, 1080], mode: outbound  }
        my_thumb_webp:
            format: webp
            quality: 100
            filters:
                thumbnail: { size: [1024, 786], mode: outbound  }
        reduc:
            quality: 85
            filters:
                scale:
                    dim: [ 1024, 786 ]
    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%/public"