vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        cars:
            uri_prefix: '%app.path.images_directory%'
            upload_destination: '%kernel.project_dir%/public%app.path.images_directory%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
